apiVersion: v1
kind: Pod
metadata:
  name: devops-demo-pod
  namespace: devops
spec:
  containers:
    - image: IMAGE:TAG
      name: krishnadevops.azurecr.io/devopsagent:v4
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
  nodeSelector:
    kubernetes.io/os: linux